name: DockerHub Publish

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/docker-demo

jobs:
  build-and-push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ github.ref_name }}