name: Docker Publish

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          REPO=ghcr.io/${{ github.repository_owner }}/docker-spring-demo
          
          IMAGE=$REPO:latest docker compose build app
          docker push $REPO:latest
          
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=${{ github.ref_name }}
            IMAGE=$REPO:$TAG docker compose build app
            docker push $REPO:$TAG
          fi